// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxqaijpfogbxlmghjqin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4cWFpanBmb2dieGxtZ2hqcWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MTI3NjIsImV4cCI6MjA3ODE4ODc2Mn0.aBr5ZRVugaYJZKIcCWsB7lSackJ-4F69rW1JerHSsRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});